### ISSUE TITLE
Customer Account API

### ISSUE THREAD

**Issue by harishvitta** [Shopify/checkout-sheet-kit-swift#165]
Hi Team,

When can we expect Customer Account API integration in [checkout-sheet-kit](https://github.com/Shopify/mobile-checkout-sdk-ios) or [mobile-buy-sdk-ios](https://github.com/Shopify/mobile-buy-sdk-ios)?

Also, will it be passwordless login functionality?

**Comment by kiftio** [comment]
Hi @harishvitta we have a couple of dependencies on other teams completing projects before we can start this work. So I don't think we have a timeline just yet.

It'd be passwordless for shops using new customer accounts, via the [customer account API](https://shopify.dev/docs/api/customer) where customers will likely be redirected to the login page in a WebView for the first step.

**Comment by harishvitta** [comment]
@kiftio Thanks for the update.
