### ISSUE TITLE
UI discrepancy between UIKit and SwiftUI

### ISSUE THREAD

**Issue by joshgare** [Shopify/checkout-sheet-kit-swift#167]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

2.0.1

### Steps to Reproduce

- Display sheet via Swift UI
- Display sheet via UIKit
- Compare navigation bars

### Expected Behavior

Navigation bar on UIKit sheet to filled in on presentation, not just when the checkout scrolls down.

### Actual Behavior

UIKit sheet displays a clear navigation bar on presentation which looks off. When you scroll down the on the UIKit sheet the navigation bar fills in. This feels a buggy and looks off which is not desired in a checkout flow.

### Screenshots/Videos/Log output

1. Swift UI on present (looks good)

![Simulator Screenshot - iPhone 15 Pro - 2024-05-08 at 10 25 19](https://github.com/Shopify/checkout-sheet-kit-swift/assets/113687/b3bde208-0e0d-4d75-b8b1-b70a94bd11c6)

2. UIKit on present (looks off)

![Simulator Screenshot - iPhone 15 Pro Max - 2024-05-08 at 14 01 02](https://github.com/Shopify/checkout-sheet-kit-swift/assets/113687/7de3fa2b-fd2c-4313-8b51-06d4c8aff2a2)

**Comment by markmur** [comment]
Thanks @joshgare. I'm updating our sample app in [this PR](https://github.com/Shopify/checkout-sheet-kit-swift/pull/168) to include an example of this flow. Would you say that the code here is similar to what you're doing?

The background color of the checkout sheet should be set to `.systemBackground` by default. Are you overriding the configuration at all?

You can explicitly set this in your application:

```swift
ShopifyCheckoutSheetKit.configure {
    $0.backgroundColor = .white
}
```

**Comment by joshgare** [comment]
@markmur just coming back to this - we updated the SDK to 3.0.1 and added the following.

```
ShopifyCheckoutSheetKit.configure {
    $0.backgroundColor = .white
}
```

However we're still seeing the UI issue when presenting the modal via UIKit.


https://github.com/Shopify/checkout-sheet-kit-swift/assets/113687/cf81dc8b-3d7d-48b0-a8db-8ae8ed669895
