### ISSUE TITLE
Receiving checkoutLiquidNotMigrated error even though I actually migrated the store

### ISSUE THREAD

**Issue by matteoSANE** [Shopify/checkout-sheet-kit-swift#174]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

2.0.1

### Do you have a minimum reproducible example?

I'm building a mobile app for my shopify store. In order to provide the best checkout experience I've integrated Checkout Sheet Kit for Swift. At the moment my store is using checkout.liquid, I’m planning to make the final upgrade to checkout extensibility. I made some test but even though I switch to checkout extensibility publishing my theme Checkout Sheet Kit for Swift give me this error:  The checkout url provided has resulted in an error. The store is still using checkout.liquid, whereas the checkout SDK only supports checkout with extensibility.

### Steps to Reproduce

Have a store currently using checkout.liquid
Publish the theme on `Customize your checkout `settings panel.
Open a native checkout dialog using the present function.

### Expected Behavior

I want to open a native checkout dialog after I switch from checkout.liquid to checkout extensibility

### Actual Behavior

When I open a native checkout dialog using the present function I'm getting back this error:
`The checkout url provided has resulted in an error. The store is still using checkout.liquid, whereas the checkout SDK only supports checkout with extensibility.`
even though I actually did the switch

### Storefront domain

https://casinetto.myshopify.com

**Comment by kiftio** [comment]
@matteoSANE could you provide your shop URL, so we can take a look at the config and double check you're correctly setup on extensibility? Thanks

**Comment by matteoSANE** [comment]
https://casinetto.myshopify.com/

> @matteoSANE could you provide your shop URL, so we can take a look at the config and double check you're correctly setup on extensibility? Thanks

**Comment by kiftio** [comment]
Thanks,

The shop looks like it's still on checkout.liquid. If you go to the shop's admin, and then to `Settings` > `Checkout`, you should see a message `Upgrade to Checkout Extensibility`.

The message seems to say you need to publish your draft to upgrade

**Comment by kiftio** [comment]
OK thanks for clarifying. 

As you require logged in users for checkout, are you using multipass URLs?

**Comment by matteoSANE** [comment]
Yes. I need it and I’m using multipass

**Comment by kiftio** [comment]
That's good to hear. I think you're right about the error message being misleading. We'll be improving error messages in the next release
