### ISSUE TITLE
Preloading checkout triggers an SMS with Shop Pay verification code 

### ISSUE THREAD

**Issue by maxmamis** [Shopify/checkout-sheet-kit-swift#179]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

3.0.0

### Steps to Reproduce

In many cases when the `preload` method is called, the user is sent an OTP code for shop pay despite not yet opening the checkout view controller. This is disconcerting to the user, who is not expecting to get an SMS at this point and has nothing visible to use it for.

Steps to reproduce:
1. With something in your cart, open the Shopify checkout sheet once and then close it. (This step might not be necessary, but for me it always triggers the bug. I'm not sure why.) 
2. Perform an action that causes the app to call `ShopifyCheckoutSheetKit.preload` again (e.g. adding something to the cart)

### Expected Behavior

Nothing happens visibly, checkout sheet preloads in background

### Actual Behavior

 I receive a text message of the format "123456 is your Shop verification code"

### Screenshots/Videos/Log output

https://github.com/Shopify/checkout-sheet-kit-swift/assets/3718504/d9716cbb-2051-47ad-af14-68ab06378afa

### Storefront domain

yaysay.myshopify.com

**Comment by kiftio** [comment]
A fix has been deployed for this issue, but I haven't had chance to validate it yet. Let us know if you're still seeing the issue

**Comment by DylanVann** [comment]
@kiftio I'm still seeing this issue

I am using https://github.com/Shopify/checkout-sheet-kit-react-native but I've checked the Pod is on version `3.0.1`
