### ISSUE TITLE
Login customer using their access token 

### ISSUE THREAD

**Issue by developerjigr** [Shopify/checkout-sheet-kit-swift#188]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

latest

### Steps to Reproduce

Set `X-Shopify-Customer-Access-Token` header.
Open Checkout Web View

How do we log in the customer automatically now?

### Expected Behavior

  Pass header for customer access token and it should log in the customer automatically - Before we used to be able to pass `X-Shopify-Customer-Access-Token`

### Actual Behavior

User needs to log in every time

### Storefront domain

All

**Comment by developerjigr** [comment]
> Same issue here. any update?

Shopify has gone too mainstream to think about us poor developers 😂 I feel like Oliver Twist. - @shopify please would it be possible for you to ask someone from your mobile iOS team working on the checkout WebKit project these questions, thank you! And then can you do it?

**Comment by kiftio** [comment]
Apologies for the delayed response

Unfortunately the `X-Shopify-Customer-Access-Token` header is not supported in checkout extensibility, in web or in Checkout Sheet Kit.

There will be an alternative mechanism for logging customers in, although it wont be header based. Instead when you associate a customer with a cart via [customer access token](https://shopify.dev/docs/api/storefront/2024-07/input-objects/CartBuyerIdentityInput#field-customeraccesstoken) the customer will be authenticated when they land in checkout. We don't expect any additional changes to your app will be required.

I'm afraid I can't give an exact timeline, other than to say it's currently being worked on.
