### ISSUE TITLE
Cart buyer identity is not pre-filled in the checkout

### ISSUE THREAD

**Issue by ShoMasegi** [Shopify/checkout-sheet-kit-swift#189]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

3.0.1 (latest)

### Reproducible sample code

MobileBuyIntegration Sample code

### Steps to Reproduce

1. Create a cart with `buyerIdentity` using the cartCreate API.
2. Show CheckoutSheet using the cart's `checkoutUrl`.
3. Do not pre-fill the buyerIdentity address (only pre-fill the email).

### Expected Behavior

`buyerIdentity` data in Cart should be pre-filled including address in checkout

### Actual Behavior

Do not pre-fill the buyerIdentity address (only pre-fill the email).

### Screenshots/Videos/Log output

https://github.com/Shopify/checkout-sheet-kit-swift/assets/12663296/2c5233d8-6f8b-4d20-b90a-19936d151029

**Comment by markmur** [comment]
Adding a `PHONE` field will mostly likely fix this if the phone field is required for in your storefront checkout settings.

Prefilled address information is only presented when complete + valid.

You can find these settings under `/settings/checkout` in the admin for your store.

<img width="721" alt="image" src="https://github.com/Shopify/checkout-sheet-kit-swift/assets/2034704/3de67438-c60f-4f64-b990-518c20bf8eb0">

**Comment by ShoMasegi** [comment]
I tried adding a phone number to the deliveryAddressPreference address and changing the settings, but the same issue occurred.

**Comment by ShoMasegi** [comment]
Yes.
I'm using the address returned as `ShoppingAddress` in the PixelEvent `checkout_address_info_submitted`.
![スクリーンショット 2024-07-12 1 22 12](https://github.com/Shopify/checkout-sheet-kit-swift/assets/12663296/93d0dbaf-b0d3-4de0-9ef6-149ee83df100)

**Comment by sabir-nagarro** [comment]
I am also facing the issue. although @markmur  adding phone field some times work.

**Comment by markmur** [comment]
Hey @ShoMasegi, 

Looks like we don't have the `PHONE` field from `Storefront.xcconfig` wired up in our sample app. I've opened #193 to implement it.

The buyer experience should look like this when the address is valid (including the phone field):

<img width="676" alt="image" src="https://github.com/user-attachments/assets/816d5046-5f8a-49d2-bb22-874a7b96af78">

**Comment by ShoMasegi** [comment]
@markmur 
Here is my storefront URL: kauche-dev.myshopify.com

**Comment by kiftio** [comment]
Hi @ShoMasegi Could you provide a cart ID or checkout URL for a time when you're able to reproduce it (for a product with correct shipping rates)? We should be able to check our logs to find out what happened

Can you also confirm if it's consistently happening, or something a bit more intermittent?

**Comment by ShoMasegi** [comment]
Hi @kiftio 
> Could you provide a cart ID or checkout URL for a time when you're able to reproduce it (for a product with correct shipping rates)?

CheckoutURL: https://kauche-dev.myshopify.com/cart/c/Z2NwLWFzaWEtc291dGhlYXN0MTowMUozNVQwQTYwRkcyUVNFVFFRSEo3VEdIWA?key=db938a589e024329a78e6ee827a5aa40

> Can you also confirm if it's consistently happening, or something a bit more intermittent?

It's consistently happening

**Comment by kiftio** [comment]
OK, the carts team took a look through the logs and found an error related to some items in the cart being unable to ship from any location. They believe that this is the root cause of the issue. 

They also mentioned that they're going to look into returning userErrors in this case, so there's more clarity on what has gone wrong.

**Comment by dcugalj** [comment]
Just to add here. By looking at [Splunk logs](https://logs.shopify.io/en-US/app/search/search?sid=1722465250.175050_BBD14E9E-A5FD-478D-8EBA-0A4BA2F3E446) for the `cartCreate` mutation that created cart with id `Z2NwLWFzaWEtc291dGhlYXN0MTowMUozNVQwQTYwRkcyUVNFVFFRSEo3VEdIWA`, I see some violations coming from `DefaultDeliveryPolicy`:

```
  [ViolationLogger] found: violation_type="UnresolvableTerm" violation_code="delivery.no_delivery_strategy_available" violation_msg="No available delivery strategy found." violation_target="$.delivery.deliveryLines"
```

This could be cause by some fulfillment checks introduced in this [PR](https://github.com/Shopify/shopify/pull/520900). @KevenLYF, do you have more context on this? 

I believe the root cause is somewhere around here, but I do not have much context on it. @deborasetton, do you know under what conditions `missing_method_definitions` error occurs:

```
 [Delivery::Domain::FilterApplicableMethodDefinitions] No applicable method definitions found. Trying fallback strategy: Delivery::Domain::WeightBasedNextHeaviestStrategy
{}
 [Delivery::Domain::FilterApplicableMethodDefinitions] Categorizing method definitions (logging the first ten)
{"delivery_allocation_token":"8998f2ee0ace28a1e1e3c704d45d6d75","applicable_method_definitions":[],"applicable_method_definitions_size":0,"not_applicable_method_definitions":[{"name":"partner shipping rate provider","type":"dynamic","id":401825235097,"failure_reason":"method_does_not_meet_required_throughput","failed_conditions":null}],"not_applicable_method_definitions_size":1}
 [Delivery::Processes::FindAllocationPlanForDeliverable] Delivery method consolidation result
{"option_count":0,"no_rates_reason":"missing_method_definitions"}
```

If this error is actionable, we should return it in the `cartCreate` mutation response.

**Comment by ShoMasegi** [comment]
Could you please advise on the next steps I should take? 
Should I wait for further information from regarding the return userErrors?
