### ISSUE TITLE
Can we change Pay Now Button Color?

### ISSUE THREAD

**Issue by musharaf-at-NGI** [Shopify/checkout-sheet-kit-swift#190]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

2.0.1

### Steps to Reproduce

Not able to change Pay Now Button Color with Existing Properties

### Expected Behavior

There should be a property to change button Pay Now Color

### Actual Behavior

Not able to change Pay Now Button Color with Existing Properties

### Screenshots/Videos/Log output

<img width="331" alt="image" src="https://github.com/Shopify/checkout-sheet-kit-swift/assets/163538488/92fb0e4f-fb69-461a-9ecf-ea7a6f563adf">

### Storefront domain

https://revibe-me.myshopify.com/

**Comment by kiftio** [comment]
If you use the web [color scheme](https://github.com/Shopify/checkout-sheet-kit-swift/issues/190) you'll inherit the colors from your desktop store, that you set in the checkout editor:

<img width="356" alt="Screenshot 2024-07-11 at 09 10 32" src="https://github.com/Shopify/checkout-sheet-kit-swift/assets/15106863/2a799c86-e073-4e35-b0ba-4f1476ccd7ed">

We don't have Checkout Sheet Kit specific branding/color overrides yet for light/dark color schemes, but it's something that's planned.
