### ISSUE TITLE
Camera is opening as Live Broadcast Video instead of normal Camera to take picture.

### ISSUE THREAD

**Issue by AsimNGI** [Shopify/checkout-sheet-kit-swift#203]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

2.0.1

### Steps to Reproduce

1. Open Checkout
2. Go with any installment plan, in my case it's Tamara.
3. Tamara asks for ID Verification where the camera opens
4. When camera opens it opens as Live broadcast video instead of Camera to take picture of ID.

### Expected Behavior

Camera should open normal Camera to take pictures of ID instead of opening Live Broadcast Video.

### Actual Behavior

When Opening camera on checkout it opens Live broadcast video instead of Camera to take picture of ID on Tamara.

### Storefront domain

https://revibe.me/

**Comment by markmur** [comment]
Hey @AsimNGI, can you share a screen recording?

This is an issue with Tamara, as this code would be coming from an external source.

**Comment by AsimNGI** [comment]
Hello @***@***.*** ***@***.***>,

I've seen the AllowsInlineMediaPlayback Pull Request
<https://github.com/Shopify/checkout-sheet-kit-swift/commit/406cb4960c8375c48fe88dac888f44f29dd96df9>.
Can you please share the expected time for the new release?

**Comment by markmur** [comment]
This should now be fixed as of [3.0.2](https://github.com/Shopify/checkout-sheet-kit-swift/releases/tag/3.0.2).

It can take about an hour or so to propagate the new version of the cocoapod. Let us know if this works for you 👍

**Comment by AsimNGI** [comment]
Thanks Mark,

The issue is fixed and working as expected on iOS, however I've initiated 1
more issue regarding Camera Permission:
https://github.com/Shopify/checkout-sheet-kit-android/issues/113 on
Android. Please look into this matter on urgent basis as we are losing 20%
of orders on daily basis.
Thanks & Regards,
