### ISSUE TITLE
iDEAL payments do not function

### ISSUE THREAD

**Issue by joshgare** [Shopify/checkout-sheet-kit-swift#213]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

3.0.4

### Steps to Reproduce

1. Create a checkout
2. Select iDEAL as a payment provider
3. Select review order
4. Checkout doesnt navigate to iDEAL hosted page to complete payment

### Expected Behavior

1. Create a checkout
2. Select iDEAL as a payment provider
3. Select review order
4. Navigate to iDEAL payment page to complete payment

### Actual Behavior

When trying to use iDEAL as a payment provider you are not navigated to the iDEAL hosted payment page to complete the payment. 

### Screenshots/Videos/Log output

https://github.com/user-attachments/assets/d95162c6-503f-4366-8eb4-49b7b6a81185

### Storefront domain

perfect-eyelash-hq.myshopify.com

**Comment by markmur** [comment]
Hey @joshgare, was this a false alarm or are you still having issues?

**Comment by joshgare** [comment]
@markmur this was a false alarm - but we are having issues with iDEAL payments in general though as they don't permit payments to be completed within a webview as they use custom private url scheme to deep link to Dutch banks.

We've got a draft PR which I will open shortly with a work around for this but would love Shopify's thoughts on this once I've done so.

**Comment by joshgare** [comment]
Here is said PR @markmur - https://github.com/Shopify/checkout-sheet-kit-swift/pull/215 +1
