### ISSUE TITLE
Amazon Pay is not showing up on the checkout page even though this is a Japanese store.

### ISSUE THREAD

**Issue by natumn** [Shopify/checkout-sheet-kit-swift#238]
### What area is the issue related to?

Checkout Sheet Kit

### What version of Checkout Sheet Kit are you using?

2.0.1

### Steps to Reproduce

Display the checkout page of a Japanese store with Amazon Pay enabled using the checkout sheet kit.

### Expected Behavior

For Japanese stores, Amazon Pay is displayed.

### Actual Behavior

Amazon Pay is not displayed only when using the Checkout Sheet Kit, even though this is a Japanese store.

### Screenshots/Videos/Log output

| Expected | Actual |
| ---- | ---- |
| <img width="300" src="https://github.com/user-attachments/assets/781f16de-a9f4-4b86-9fea-0e2dde3da431"></img> | <img width="300" src="https://github.com/user-attachments/assets/50d4340c-b24c-42fe-ac7c-98f6b6dfc07f"></img> |
| <img width="300" src="https://github.com/user-attachments/assets/e53c2436-e2d5-4480-9c8b-8902a6683be4"></img> | <img width="300" src="https://github.com/user-attachments/assets/eb428242-f773-42da-a306-3c7e96abc109"></img> |

### Storefront domain

For example, stores like geekshop.infolens.com are affected.

**Comment by kiftio** [comment]
Hi @natumn unfortunately this payment method has incompatibility issues with checkout extensibility, which means we're unable to include it in Checkout Sheet Kit checkouts

**Comment by kiftio** [comment]
A deprecation notice related to this related to this payment method should now have been sent.

There are some relevant docs [here](https://help.shopify.com/en/manual/payments/accelerated-checkouts/amazonpay/amazon-pay#third-party).

So I'll close this issue
